name: Python Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Updated to latest version

    - name: Set up Python 3.10
      uses: actions/setup-python@v4  # Updated to latest version
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # Check for critical errors (syntax errors, undefined names)
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Run full linting, but allow warnings for review
        flake8 . --count --max-complexity=10 --max-line-length=88 --statistics

    - name: Test with pytest
      run: |
        export PYTHONPATH=$PWD
        pytest app/tests